#!/bin/bash

# Copyright (c) 2016 Rafał Pocztarski
# Released under MIT License (Expat) - see:
# https://github.com/rsp/node-static-http-servers/blob/master/LICENSE.md

fail () {
  echo TESTING FAILED
  exit 1
}

for i in connect.js express.js estatic.js; do
    ./test-server $i || fail
done
echo TESTS PASSED
